steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloud-run-vision', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cloud-run-vision']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'cloud-run-vision', '--image', 'gcr.io/$PROJECT_ID/cloud-run-vision:latest', '--region', 'us-central1', '--allow-unauthenticated']
images: ['gcr.io/$PROJECT_ID/cloud-run-vision']